server:
  port: 8888
app:
  api-prefix: /api/v1
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: book-service
          uri: http://localhost:8081
          predicates:
            - Path=${app.api-prefix}/books/**
          filters:
            - StripPrefix=2
        - id: order-service
          uri: http://localhost:8082
          predicates:
            - Path=${app.api-prefix}/books/**
          filters:
            - StripPrefix=2
